# create a program that will play the “cows and bulls” game with the user. The game works like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
# For every digit that the user guessed correctly in the correct place, they have a “cow”.
# For every digit the user guessed correctly in the wrong place is a “bull.”
# Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
# Once the user guesses the correct number, the game is over.
# Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...


import random

guess_count = 0
cow = 0
bull = 0
def cowsBulls(number,rand):
    for i in range(0,4):
        if number[i] == rand[i]:
            global cow
            cow += 1
        elif number[i] in rand:
            global bull
            bull += 1
        else:
            pass
    if(cow == 4): return True
    return False
rand = random.randrange(1000,9999)
print("random: ", rand)
print("Welcome to the Cows and Bulls Game!")

while True:
    number = input("Enter number (4 digit): ")
    if len(number) != 4:
        continue
    cow = 0
    bull = 0
    result = cowsBulls(str(number), str(rand))
    print ("cows:", cow, "bulls: ", bull)
    guess_count += 1
    if(result):
        print("Successfully guessed with {0} atempts".format(guess_count))
        break
